repos:
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.14.2
  hooks:
    # Run the linter.
    - id: zizmor
      args: [--persona=pedantic]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: forbid-submodules
    - id: trailing-whitespace
